apiVersion: v1
kind: PersistentVolume
metadata:
  name: review-ebs-pv
spec:
  volumeMode: Filesystem
  storageClassName: gp2
  capacity:
    storage: 5Gi # 볼륨의 크기
  accessModes:
    - ReadWriteOnce # 하나 Pod에 마운트
  awsElasticBlockStore:
    volumeID: vol-0e90f79bfaedb433f
  persistentVolumeReclaimPolicy: Retain